### ISSUE TITLE
KaroAPI Cross-Domain-Post testen

### ISSUE THREAD

**Issue by ultimate** [ultimate/KaroMUSKEL#11]

**Comment by ultimate** [comment]
von @xosofox:

    game = {
        "name":"Mit der API erstellt",
        "players":[1,1411],
        "map":101,
        "options":{
            "startdirection":"classic",
            "withCheckpoints":true,
            "zzz":4,
            "crashallowed":"forbidden"
        }}

:arrow_right: POST mit Content-Type: "application/x-www-form-urlencoded; charset=UTF-8"

**Comment by ultimate** [comment]
Rückmeldung im Firefox:

*Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://www.karopapier.de/api/game/add.json. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).*

@xosofox: Kannst du das ändern?

**Comment by Xosofox** [comment]
Retry

**Comment by ultimate** [comment]
Request kommt durch, liefert aber 401 "not logged in".
Es scheint also als wird der Cookie nicht übertragen. Sollte mit dem "withCredentials" Flag zu beheben sein (http://stackoverflow.com/questions/10230341/http-cookies-and-ajax-requests-over-https/10249123)

**Comment by Xosofox** [comment]
Vgl. Beispiel des "votings" der Map, zu finden auf der normalen Spielansicht

		$.ajax({
			url: voteurl,
			data: "vote="+vote,
			type: 'POST',
			xhrFields: {
				withCredentials: true
			},
			success: function(data) {
				//console.log("gut",data);
				$('#mapvote').trigger("newdata",data);
			},
			error: function(data) {
				//console.log("bad",data);
			},
			dataType: "json"
		});

**Comment by ultimate** [comment]
Ja, genau so (nur ohne jquery) hab ich es gemacht. Scheint aber doch nicht so einfach, denn
- wenn ich das withCredentials-Flag setze, kommt die folgende Fehlermeldung:

    *Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://www.karopapier.de/api/game/add.json. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' stimmt nicht mit '***' überein).*

Scheinbar ist der Grund dafür, dass "withCredentials" nicht mit Access-Control-Allow-Origin "*" kombinierbar ist. (siehe http://stackoverflow.com/questions/19743396).

Ich muss also auf eine andere Alternative umsteigen. Da ich jetzt aber erst einmal davon ausgehe, dass das mit dem Post auf die eine oder andere Weise klappen wird, kann ich mich ja erstmal auf die Gestaltung der Oberfläche und die eigentliche Spiele-Serien-Logik stürzen. Der Post klappt ja auf jedenfall, wenn er direkt von Karopapier.de kommt.

**Daher würde ich dich bitten, dass du einen html/php-Frame für den KaroMUSKEL erstellst. Dabei musst du auch nich so viel beachten, wichtig ist nur:**

- die beiden folgenden scripts eingebunden in der aufgelisteten Reihenfolge (den Rest füge ich selbst hinzu)

        <script type="text/javascript" src="http://cdn.rawgit.com/ultimate/syncnapsis/71656b61de31b1c0fb0b1d2680ea32bec743fef8/syncnapsis-core/syncnapsis-core-utils/src/main/webapp/scripts/util/Requests.js"></script>
        <script type="text/javascript" src="http://rawgit.com/ultimate/KaroMUSKEL/V4.x/KaroMUSKEL/KaroMUSKEL.js"></script>;
        

- ein container in den der KaroMUSKEL seinen Inhalt reinpusten kann, z.B. #KaroMUSKELWrapper (analog zum Chat)
- nice-to-have credits in der Art

        KaroMUSKEL is brought to you by <a href="https://github.com/ultimate">ultimate</a><br>

- nice-to-have der script-part mit

        ME.login = "ultimate";
        ME.id =1411;
		
Auf diese Weise:

- kann ich okal das Layout und die Logik testen
- kann ich das Script auf github pushen und anschließend live auf der Karo vollständig testen
- muss es kein unsicheres Cross-Domain-Gedöns mehr geben

**Comment by ultimate** [comment]
So, jetzt ist es ja kein Cross-Domain-Post mehr, aber es funzt trotzdem noch nicht (ganz):

- http://www.karopapier.de/api/game/add.json mit ````withCredentials=false```` :arrow_right:  404 (Not Found)<br>kann es sein, dass add.json noch nur unter reloaded verfügbar ist?
- http://www.karopapier.de/api/game/add.json mit ````withCredentials=true```` :arrow_right:  404 (Not Found)<br>kann es sein, dass add.json noch nur unter reloaded verfügbar ist?
- http://reloaded.karopapier.de/api/game/add.json mit ````withCredentials=false```` :arrow_right:  401 (Unauthorized)<br>"not logged in?" (ok, das war zu erwarten...)
- http://reloaded.karopapier.de/api/game/add.json mit ````withCredentials=true```` :arrow_right:  404 (Not Found)<br>*A wildcard '***' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://www.karopapier.de' is therefore not allowed access.*

@Xosofox: kannst du das '*' bei 'Access-Control-Allow-Origin' dann wieder rausnehmen? Das ist jetzt ja nicht mehr nötig und scheint ja eh in zusammenhang mit ````withCredentials=true```` verboten zu sein.

**Comment by Xosofox** [comment]
Das Script ist natürlich schon da - aber hört nur auf method: POST. Ein einfach er Aufruf der URL erzeugt ja einen GET request, und da hört keiner drauf.
Wenn Du also tatsächlich method/type: POST gesetzt hast, dann verwandelt Dir irgendwas andere sden Request in ein GET - schau mal im DevTool des Browsers Deiner Wahl, was da über das Netz geht

**Comment by ultimate** [comment]
Ich schau es mir nochmal an, sobald ich wieder in unzensiertem Netz unterwegs bin :wink:
Kannst du trotzdem das 'Access-Control-Allow-Origin' wieder auf 'http://www.karopapier.de" zurück setzen?

**Comment by ultimate** [comment]
PS: natürlich sind alle Anfragen oben per POST gemacht.

**Comment by Xosofox** [comment]
Gut - hab herausgefunden, woran es liegt.
Sobald was nicht stimmt, werf ich nen 404 - auch wenn das völlig gelogen
ist und ein 4xx sein sollte.

"Korrektes" implementierungsbeispiel folgt - ich bau da gerade was :D

Am 16. Juni 2015 um 15:04 schrieb ultimate <notifications@github.com>:

**Comment by ultimate** [comment]
Hehe, alles klar, danke! :grinning:

**Comment by Xosofox** [comment]
$.ajax({
        url: "http://www.karopapier.de/api/game/add.json",
        data: "game="+JSON.stringify(game),
        method: "POST",
        type: "POST",
        xhrFields: {
            withCredentials: true
        },
        success: function(data) {
            console.log("gut",data);
        },
        error: function(data) {
            console.log("bad",data);
        },
        dataType: "json"
    });

**Comment by ultimate** [comment]
Ah, ich sehe, wo das Problem liegt: ich habe einfach das game gepostet (ohne ````game=...````)

**Comment by ultimate** [comment]
Hier das komplette Beispiel aus der Gamma Erstellen Seite:



function sendData() { game.name = $('#name').val(); game.map = parseInt($('#mapId').val()); game.players = selectedUsers.pluck("id"); game.options={}; game.options.startdirection=$('#startdirection').val(); game.options.withCheckpoints=$('#withCheckpoints').prop("checked"); game.options.zzz=parseInt($('#zzz').val()); game.options.crashallowed=$('#crashallowed').val();
$.ajax({ url:"/api/game/add.json", dataType:'json', data:'game=' + JSON.stringify(game), type:'POST', xhrFields:{ withCredentials:true }, success:function (data, textStatus, jqXHR) { notifier.addNotification("Spiel erstellt: " + data.game.id + " - " + data.game.name, "info"); $('#sendit').removeAttr("disabled"); }, error:function (XMLHttpRequest, textStatus, errorThrown) { notifier.addNotification("Fehler: " + XMLHttpRequest.responseText, "error"); $('#sendit').removeAttr("disabled"); } });
}

**Comment by Xosofox** [comment]
Ja, das is mit allen optionen - oben mein Beispiel ist "Das nötigste": Name, Spieler-IDs und ne MapID. Das reicht und erstellt ein Spiel mit default

**Comment by ultimate** [comment]
Wird zu Hause getestet, aber ich vermute es lag an dem ````game=...````

**Comment by ultimate** [comment]
So, jetzt hab ich den (dämlichen) Fehler gefunden!
Wenn man seinen eigenen Code kopiert, sollte man das auch richtig machen...
Es lag schlussendlich daran, dass ich

    request.headers = { "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8" }; 

statt

    request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");

verwendet habe. Im original Code wird das Array korrekt in mehrere ````setRequestHeader(...)```` umgewandelt, das habe ich aber verpeilt...

**Comment by Xosofox** [comment]
Sehr schön! Weiter geht's!
