### ISSUE TITLE
Login nicht möglich

### ISSUE THREAD

**Issue by ultimate** [ultimate/KaroMUSKEL#76]
Nach der Server-Migration ist der Login nicht mehr möglich

**Comment by xosofox** [comment]
Falls es was hilft: Seit Oktober geht auch bei allen Calls ein zusätzliches AUTH-Alternative zu den Cookies:

Siehe https://www.karopapier.de/api/

Bei jedem Request über die Header "X-Auth-Login" und "X-Auth-Password" die Daten setzen. Erspart jegliches Cookie-Gehampel. Beispiel in CURL:

    curl https://www.karopapier.de/api/user/check -H "x-auth-login: Didi" -H "x-auth-password: password2028"

**Comment by ultimate** [comment]
Hmm... Hätte das Ticket wohl mal schließen sollen, als ich es gefixt habe ;-) Das hier war tatsächlich eine andere kleine Umstellung...

Habe mal ein neues Ticket erstellt: #81
